name=Audio
version=1.0.0
author=XRADIO Technology
maintainer=XRADIO Technology <support@xradiotech.com>
sentence=Audio library for XR871 Arduino
paragraph=Provides I2S/DMIC audio input/output for XR871. Supports WAV, MP3, AAC playback and recording.
category=Signal Input/Output
url=https://github.com/XradioTech/XR871-ARDUINO
architectures=xr871
includes=Audio.h
