name=MDNS
version=1.0.0
author=XRADIO Technology
maintainer=XRADIO Technology <support@xradiotech.com>
sentence=mDNS library for XR871 Arduino
paragraph=Provides mDNS service discovery functionality. Compatible with ESP32 mDNS API.
category=Communication
url=https://github.com/XradioTech/XR871-ARDUINO
architectures=xr871
includes=MDNS.h
