name=DNSServer
version=1.0.0
author=XRADIO Technology
maintainer=XRADIO Technology <support@xradiotech.com>
sentence=DNS server library for XR871 Arduino
paragraph=Provides DNS server functionality for captive portal applications.
category=Communication
url=https://github.com/XradioTech/XR871-ARDUINO
architectures=xr871
includes=DNSServer.h
