name=Camera
version=1.0.0
author=XRADIO Technology
maintainer=XRADIO Technology <support@xradiotech.com>
sentence=Camera library for XR871 Arduino
paragraph=Provides CSI camera interface for OV2640, OV7670 and other camera sensors. Compatible with ESP32 Camera API.
category=Sensors
url=https://github.com/XradioTech/XR871-ARDUINO
architectures=xr871
includes=Camera.h
